-- Write your PostgreSQL query statement below
WITH POSITIVE AS ( 
    SELECT PATIENT_ID, MIN(TEST_DATE) AS POS_DATE
    FROM COVID_TESTS
    WHERE RESULT = 'Positive'
    GROUP BY PATIENT_ID
),
NEGATIVE AS ( 
    SELECT A.PATIENT_ID, MIN(A.TEST_DATE) AS NEG_DATE
    FROM COVID_TESTS A 
    JOIN POSITIVE B ON A.PATIENT_ID = B.PATIENT_ID AND A.TEST_DATE > B.POS_DATE
    WHERE RESULT = 'Negative'
    GROUP BY A.PATIENT_ID
)
SELECT A.PATIENT_ID, A.PATIENT_NAME, A.AGE, NEG_DATE - POS_DATE AS RECOVERY_TIME
FROM PATIENTS A 
JOIN POSITIVE B ON A.PATIENT_ID = B.PATIENT_ID
JOIN NEGATIVE C ON B.PATIENT_ID = C.PATIENT_ID
ORDER BY RECOVERY_TIME, A.PATIENT_NAME;